package edu.pdx.cs.joy.jdbc;

import java.sql.SQLException;
import java.util.List;

/**
 * Data Access Object interface for managing AcademicTerm entities in the database.
 */
public interface AcademicTermDAO {

  /**
   * Saves an academic term to the database.
   * The term's ID will be automatically generated by the database and set on the object.
   *
   * @param term the academic term to save
   * @throws SQLException if a database error occurs
   */
  void save(AcademicTerm term) throws SQLException;

  /**
   * Finds an academic term by its ID.
   *
   * @param id the ID to search for
   * @return the academic term with the given ID, or null if not found
   * @throws SQLException if a database error occurs
   */
  AcademicTerm findById(int id) throws SQLException;

  /**
   * Finds an academic term by its name.
   *
   * @param name the name to search for
   * @return the academic term with the given name, or null if not found
   * @throws SQLException if a database error occurs
   */
  AcademicTerm findByName(String name) throws SQLException;

  /**
   * Finds all academic terms in the database.
   *
   * @return a list of all academic terms
   * @throws SQLException if a database error occurs
   */
  List<AcademicTerm> findAll() throws SQLException;

  /**
   * Updates an existing academic term in the database.
   * Uses the term's ID to identify which record to update.
   *
   * @param term the academic term to update
   * @throws SQLException if a database error occurs
   */
  void update(AcademicTerm term) throws SQLException;

  /**
   * Deletes an academic term from the database by ID.
   *
   * @param id the ID of the academic term to delete
   * @throws SQLException if a database error occurs
   */
  void delete(int id) throws SQLException;
}

