package edu.pdx.cs.joy.jdbc;

import java.sql.SQLException;
import java.util.List;

/**
 * Data Access Object interface for managing Course entities in the database.
 */
public interface CourseDAO {

  /**
   * Saves a course to the database.
   * The course's ID will be automatically generated by the database and set on the object.
   *
   * @param course the course to save
   * @throws SQLException if a database error occurs
   */
  void save(Course course) throws SQLException;

  /**
   * Finds a course by its title.
   *
   * @param title the title to search for
   * @return the course with the given title, or null if not found
   * @throws SQLException if a database error occurs
   */
  Course findByTitle(String title) throws SQLException;

  /**
   * Finds all courses associated with a specific department.
   *
   * @param departmentId the department ID to search for
   * @return a list of courses in the department
   * @throws SQLException if a database error occurs
   */
  List<Course> findByDepartmentId(int departmentId) throws SQLException;

  /**
   * Updates an existing course in the database.
   * Uses the course's ID to identify which record to update.
   *
   * @param course the course to update
   * @throws SQLException if a database error occurs
   */
  void update(Course course) throws SQLException;
}

