package edu.pdx.cs.joy.jdbc;

import java.sql.SQLException;
import java.util.List;

/**
 * Data Access Object interface for managing Department entities in the database.
 */
public interface DepartmentDAO {

  /**
   * Saves a department to the database.
   * The department's ID will be automatically generated by the database.
   *
   * @param department the department to save
   * @throws SQLException if a database error occurs
   */
  void save(Department department) throws SQLException;

  /**
   * Finds a department by its ID.
   *
   * @param id the ID to search for
   * @return the department with the given ID, or null if not found
   * @throws SQLException if a database error occurs
   */
  Department findById(int id) throws SQLException;

  /**
   * Finds a department by its name.
   *
   * @param name the name to search for
   * @return the department with the given name, or null if not found
   * @throws SQLException if a database error occurs
   */
  Department findByName(String name) throws SQLException;

  /**
   * Finds all departments in the database.
   *
   * @return a list of all departments
   * @throws SQLException if a database error occurs
   */
  List<Department> findAll() throws SQLException;

  /**
   * Updates an existing department in the database.
   *
   * @param department the department to update
   * @throws SQLException if a database error occurs
   */
  void update(Department department) throws SQLException;

  /**
   * Deletes a department from the database by ID.
   *
   * @param id the ID of the department to delete
   * @throws SQLException if a database error occurs
   */
  void delete(int id) throws SQLException;
}

