package edu.pdx.cs.joy.jdbc;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Data Access Object for managing Department entities in the database.
 * Demonstrates basic JDBC operations: CREATE, READ.
 */
public class DepartmentDAO {

  private final Connection connection;

  /**
   * Creates a new DepartmentDAO with the specified database connection.
   *
   * @param connection the database connection to use
   */
  public DepartmentDAO(Connection connection) {
    this.connection = connection;
  }

  /**
   * Drops the departments table from the database if it exists.
   *
   * @param connection the database connection to use
   * @throws SQLException if a database error occurs
   */
  public static void dropTable(Connection connection) throws SQLException {
    try (Statement statement = connection.createStatement()) {
      statement.execute("DROP TABLE IF EXISTS departments");
    }
  }

  /**
   * Creates the departments table in the database.
   *
   * @param connection the database connection to use
   * @throws SQLException if a database error occurs
   */
  public static void createTable(Connection connection) throws SQLException {
    try (Statement statement = connection.createStatement()) {
      statement.execute(
        "CREATE TABLE departments (" +
        "  id IDENTITY PRIMARY KEY," +
        "  name VARCHAR(255) NOT NULL" +
        ")"
      );
    }
  }

  /**
   * Saves a department to the database.
   * The department's ID will be automatically generated by the database.
   *
   * @param department the department to save
   * @throws SQLException if a database error occurs
   */
  public void save(Department department) throws SQLException {
    String sql = "INSERT INTO departments (name) VALUES (?)";

    try (PreparedStatement statement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
      statement.setString(1, department.getName());
      statement.executeUpdate();

      // Retrieve the auto-generated ID and set it on the department object
      try (ResultSet generatedKeys = statement.getGeneratedKeys()) {
        if (generatedKeys.next()) {
          int generatedId = generatedKeys.getInt(1);
          department.setId(generatedId);
        } else {
          throw new SQLException("Creating department failed, no ID obtained.");
        }
      }
    }
  }

  /**
   * Finds a department by its ID.
   *
   * @param id the ID to search for
   * @return the department with the given ID, or null if not found
   * @throws SQLException if a database error occurs
   */
  public Department findById(int id) throws SQLException {
    String sql = "SELECT id, name FROM departments WHERE id = ?";

    try (PreparedStatement statement = connection.prepareStatement(sql)) {
      statement.setInt(1, id);

      try (ResultSet resultSet = statement.executeQuery()) {
        if (resultSet.next()) {
          return extractDepartmentFromResultSet(resultSet);
        }
      }
    }

    return null;
  }

  /**
   * Finds a department by its name.
   *
   * @param name the name to search for
   * @return the department with the given name, or null if not found
   * @throws SQLException if a database error occurs
   */
  public Department findByName(String name) throws SQLException {
    String sql = "SELECT id, name FROM departments WHERE name = ?";

    try (PreparedStatement statement = connection.prepareStatement(sql)) {
      statement.setString(1, name);

      try (ResultSet resultSet = statement.executeQuery()) {
        if (resultSet.next()) {
          return extractDepartmentFromResultSet(resultSet);
        }
      }
    }

    return null;
  }

  /**
   * Finds all departments in the database.
   *
   * @return a list of all departments
   * @throws SQLException if a database error occurs
   */
  public List<Department> findAll() throws SQLException {
    List<Department> departments = new ArrayList<>();
    String sql = "SELECT id, name FROM departments ORDER BY id";

    try (Statement statement = connection.createStatement();
         ResultSet resultSet = statement.executeQuery(sql)) {
      while (resultSet.next()) {
        departments.add(extractDepartmentFromResultSet(resultSet));
      }
    }

    return departments;
  }

  /**
   * Extracts a Department object from the current row of a ResultSet.
   *
   * @param resultSet the result set positioned at a department row
   * @return a Department object with data from the result set
   * @throws SQLException if a database error occurs
   */
  private Department extractDepartmentFromResultSet(ResultSet resultSet) throws SQLException {
    int id = resultSet.getInt("id");
    String name = resultSet.getString("name");
    return new Department(id, name);
  }
}

