#
# $Id: GNUmakefile,v 1.3 2001-05-06 04:58:25 whitlock Exp $
#

# example leaf node for building a java package
default: all

TOPDIR=../../../..
PACKAGE=edu.pdx.cs410J.examples
JAR_FILE=examples.jar

EXTRA_JARS= \
	xerces.jar \
        mail.jar \
        activation.jar \


JAVA_CLASSES= \
        AddTwo \
        Animal \
        Ant \
        AroundTheWorld \
        ATM \
        BankAccount \
        Bee \
        Bird \
        BuildPhonebook \
        Business \
        Cereal \
        CerealComparator \
        ChatCommunicator \
        ChatListener \
        ChatMessage \
        ChatSession \
        ChatSpeaker \
        ClassComparator \
        Clock \
        Collections \
        Counter \
        CountingRace \
        Cow \
        DateDemo \
        DirectoryFilter \
        DivTwo \
        DoIFly \
        DrawCoords \
        DrawCoordsApplet \
        DrawPolygon \
        Duck \
        DumpURL \
        Farm \
        FileSystemBrowser \
        FileSystemNode \
        FileSystemTable \
        FileTableModel \
        FindClassFiles \
        FindJavaFiles \
        Flies \
        Fonts \
        FormattedDate \
        Game \
        GameConsole \
        GameConsolePriv \
        GenerateKeys \
        GuessingGame \
        Hello \
        Human \
        Insect \
        Javadoc \
        JavaFilenameFilter \
        Listener \
        LoadFromURL \
        MailFile \
        MakeJar \
        Mammal \
        McCustomer \
        McDonalds \
        McEmployee \
        GraphNode \
        ParseString \
        PassByValue \
        Person \
        PersonComparator \
        PhoneBook \
        PhoneBookEntry \
        PrintDigest \
        PrintUser \
        ReadDate \
        ReadDoubles \
        ReadFromConsole \
        ReadGraphNodes \
        Reflect \
        Resident \
        SayWhat \
        Sheep \
        SignMessage \
        SimpleDate \
        SimpleGUI \
        Speaker \
        SynchronizedATM \
        SynchronizedBankAccount \
        SystemProperties \
        TextEditor \
        Today \
        Transfer \
        TranslateCoords \
        Turkey \
        ValidateXml \
        VerifyMessage \
        WhatAmI \
        WriteDate \
        WriteDoubles \
        WriteGraphNodes \
        WriteToFile \
        WriteToHomeDir \



include $(TOPDIR)/makefiles/java.gmk

