#!/bin/sh

# Shell script to invoke glimpse using the index built in the current
# directory.
#
# For more information about glimpse see:
#
#                     http://www.webglimpse.net

glimpse -H . $*