#
# $Id: GNUmakefile,v 1.1 2001-02-19 23:45:51 whitlock Exp $
#

# example leaf node for building a java package
default: all

TOPDIR=../../../..
PACKAGE=edu.pdx.cs410J.familyTree
JAR_FILE=familyTree.jar

EXTRA_JARS= \
	xerces.jar \


JAVA_CLASSES= \
        AddPerson \
        AddPersonDialog \
        ChoosePersonDialog \
        Dumper \
        EditMarriageDialog \
        EditPersonDialog \
        FamilyTree \
        FamilyTreeApplet \
        FamilyTreeGUI \
        FamilyTreeList \
        FamilyTreePanel \
        Marriage \
        NoteMarriage \
        Parser \
        Person \
        PersonPanel \
        PrettyPrinter \
        TextDumper \
        TextParser \
        XmlDumper \
        XmlParser \


include $(TOPDIR)/makefiles/java.gmk

