#
# $Id: GNUmakefile,v 1.1 2001-07-26 01:14:42 whitlock Exp $
#

# example leaf node for building a java package
default: all

TOPDIR=../../../..
PACKAGE=edu.pdx.cs410J.core
JAR_FILE=examples.jar

JAVA_CLASSES= \
        Cereal \
        CerealComparator \
        Collections \
        DateDemo \
        DirectoryFilter \
        Farm \
        FindClassFiles \
        FindJavaFiles \
        FormattedDate \
        JavaFilenameFilter \
        ParseString \
        PersonComparator \
        ReadDate \
        ReadDoubles \
        ReadFromConsole \
        SimpleDate \
        SystemProperties \
        Today \
        WriteDoubles \
        WriteToFile \



include $(TOPDIR)/makefiles/java.gmk

