#
# $Id: GNUmakefile,v 1.3 2002-03-02 23:41:22 whitlock Exp $
#

# example leaf node for building a java package
default: all

TOPDIR=../../../..
PACKAGE=edu.pdx.cs399J.xml
JAR_FILE=examples.jar

EXTRA_JARS= \
	xerces.jar \


JAVA_CLASSES= \
        BuildPhonebook \
        Business \
        PhoneBook \
        PhoneBookEntry \
        PrintPhoneNumbers \
        Resident \
        ValidateXml \



include $(TOPDIR)/makefiles/java.gmk

