#
# $Id: GNUmakefile,v 1.3 2001-08-11 03:38:11 whitlock Exp $
#

# example leaf node for building a java package
default: all

TOPDIR=../../../..
PACKAGE=edu.pdx.cs410J.gui
JAR_FILE=examples.jar


JAVA_CLASSES= \
        ActionEventExample \
        ActionEventExample2 \
        AdjustGridLayoutGaps \
        BorderExample \
        BorderLayoutExample \
        BoxLayoutExample \
        CheckboxExample \
        CheckboxGroupExample \
        CheckboxMenuItemExample \
        ChoiceExample \
        Clock \
        DavesSocialLife \
        DialogExample \
        DrawCoords \
        DrawCoordsApplet \
        DrawPolygon \
        FileSystemBrowser \
        FileSystemNode \
        FileSystemTable \
        FileTableModel \
        FlowLayoutInCenter \
        FlowLayoutInEast \
        FlowLayoutInSouth \
        FlowLayoutExample \
        Fonts \
        GridLayoutExample \
        HeatIndex \
        JButtonExample \
        JComboBoxExample \
        JMenuExample \
        JSplitPaneExample \
        JTabbedPaneExample \
        JTextExample \
        JToolBarExample \
        JToolTipExample \
        JProgressBarExample \
        JWebBrowser \
        LabelExample \
        MenuExample \
        MenuShortcutExample \
        MouseAndKeyEvents \
        NestedFlowLayouts \
        PopupMenuExample \
        PostfixCalculator \
        SimpleGUI \
        TextAreaExample \
        TextEditor \
        TextFieldExample \
        TranslateCoords \
        WindowAdapterExample \



include $(TOPDIR)/makefiles/java.gmk

