#
# $Id: GNUmakefile,v 1.2 2001-08-11 03:34:43 whitlock Exp $
#

# example leaf node for building a java package
default: all

TOPDIR=../../../..
PACKAGE=edu.pdx.cs410J.xml
JAR_FILE=examples.jar

EXTRA_JARS= \
	xerces.jar \


JAVA_CLASSES= \
        BuildPhonebook \
        Business \
        PhoneBook \
        PhoneBookEntry \
        PrintPhoneNumbers \
        Resident \
        ValidateXml \



include $(TOPDIR)/makefiles/java.gmk

