#
# $Id: GNUmakefile,v 1.2 2002-03-02 23:40:46 whitlock Exp $
#

# example leaf node for building a java package
default: all

TOPDIR=../../../..
PACKAGE=edu.pdx.cs399J.core
JAR_FILE=examples.jar

JAVA_CLASSES= \
        Cereal \
        CerealComparator \
        Collections \
        DateDemo \
        DirectoryFilter \
        Farm \
        FindClassFiles \
        FindJavaFiles \
        FormattedDate \
        JavaFilenameFilter \
        ParseString \
        PersonComparator \
        ReadDate \
        ReadDoubles \
        ReadFromConsole \
        SimpleDate \
        SystemProperties \
        Today \
        WriteDoubles \
        WriteToFile \



include $(TOPDIR)/makefiles/java.gmk

