#
# $Id: GNUmakefile,v 1.1 2001-07-26 01:14:51 whitlock Exp $
#

# example leaf node for building a java package
default: all

TOPDIR=../../../..
PACKAGE=edu.pdx.cs410J.net
JAR_FILE=examples.jar


JAVA_CLASSES= \
        ATM \
        BankAccount \
        ChatCommunicator \
        ChatListener \
        ChatMessage \
        ChatSession \
        ChatSpeaker \
        Counter \
        CountingRace \
        DumpURL \
        Listener \
        LoadFromURL \
        McCustomer \
        McDonalds \
        McEmployee \
        Speaker \
        SynchronizedATM \
        SynchronizedBankAccount \
        Transfer \
        WriteDate \



include $(TOPDIR)/makefiles/java.gmk

