#
# $Id: GNUmakefile,v 1.1 2001-02-19 23:47:33 whitlock Exp $
#

# example top level makefile... This will just descend to a directory.
# and enable the javadocs target.
default: all

TOPDIR=.
SUBDIRS=edu
JAVADOCS=true

include $(TOPDIR)/makefiles/java.gmk

