#
# $Id: GNUmakefile,v 1.1 2001-07-26 01:14:53 whitlock Exp $
#

# example leaf node for building a java package
default: all

TOPDIR=../../../..
PACKAGE=edu.pdx.cs410J.security
JAR_FILE=examples.jar


JAVA_CLASSES= \
        Game \
        GameConsole \
        GameConsolePriv \
        GenerateKeys \
        GuessingGame \
        PrintDigest \
        PrintUser \
        SignMessage \
        VerifyMessage \
        WriteToHomeDir \



include $(TOPDIR)/makefiles/java.gmk

