#
# $Id: GNUmakefile,v 1.2 2002-03-02 23:41:19 whitlock Exp $
#

# example leaf node for building a java package
default: all

TOPDIR=../../../..
PACKAGE=edu.pdx.cs399J.security
JAR_FILE=examples.jar


JAVA_CLASSES= \
        Game \
        GameConsole \
        GameConsolePriv \
        GenerateKeys \
        GuessingGame \
        PrintDigest \
        PrintUser \
        SignMessage \
        VerifyMessage \
        WriteToHomeDir \



include $(TOPDIR)/makefiles/java.gmk

