#
# $Id: GNUmakefile,v 1.2 2002-03-02 23:41:14 whitlock Exp $
#

# example leaf node for building a java package
default: all

TOPDIR=../../../..
PACKAGE=edu.pdx.cs399J.java
JAR_FILE=examples.jar


JAVA_CLASSES= \
        AddTwo \
        Animal \
        Ant \
        Bee \
        Bird \
        Cow \
        DivTwo \
        DoIFly \
        Duck \
        Flies \
        Hello \
        Human \
        Insect \
        Javadoc \
        Mammal \
        PassByValue \
        Person \
        SayWhat \
        Sheep \
        Turkey \
        WhatAmI \


include $(TOPDIR)/makefiles/java.gmk

