#
# $Id: GNUmakefile,v 1.2 2001-07-29 04:54:27 whitlock Exp $
#

# example leaf node for building a java package
default: all

TOPDIR=../../../..
PACKAGE=edu.pdx.cs410J.gui
JAR_FILE=examples.jar


JAVA_CLASSES= \
        ActionEventExample \
        ActionEventExample2 \
        AdjustGridLayoutGaps \
        BorderLayoutExample \
        CheckboxExample \
        CheckboxGroupExample \
        CheckboxMenuItemExample \
        ChoiceExample \
        Clock \
        DavesSocialLife \
        DialogExample \
        DrawCoords \
        DrawCoordsApplet \
        DrawPolygon \
        FileSystemBrowser \
        FileSystemNode \
        FileSystemTable \
        FileTableModel \
        FlowLayoutInCenter \
        FlowLayoutInEast \
        FlowLayoutInSouth \
        FlowLayoutExample \
        Fonts \
        GridLayoutExample \
        LabelExample \
        MenuExample \
        MenuShortcutExample \
        MouseAndKeyEvents \
        NestedFlowLayouts \
        PopupMenuExample \
        PostfixCalculator \
        SimpleGUI \
        TextAreaExample \
        TextEditor \
        TextFieldExample \
        TranslateCoords \
        WindowAdapterExample \



include $(TOPDIR)/makefiles/java.gmk

