#
# $Id: GNUmakefile,v 1.1 2001-07-26 01:14:45 whitlock Exp $
#

# example leaf node for building a java package
default: all

TOPDIR=../../../..
PACKAGE=edu.pdx.cs410J.gui
JAR_FILE=examples.jar


JAVA_CLASSES= \
        ActionEventExample \
        ActionEventExample2 \
        CheckboxExample \
        CheckboxGroupExample \
        CheckboxMenuItemExample \
        ChoiceExample \
        Clock \
        DialogExample \
        DrawCoords \
        DrawCoordsApplet \
        DrawPolygon \
        FileSystemBrowser \
        FileSystemNode \
        FileSystemTable \
        FileTableModel \
        Fonts \
        LabelExample \
        MenuExample \
        MenuShortcutExample \
        MouseAndKeyEvents \
        PopupMenuExample \
        SimpleGUI \
        TextAreaExample \
        TextEditor \
        TextFieldExample \
        TranslateCoords \
        WindowAdapterExample \



include $(TOPDIR)/makefiles/java.gmk

