#
# $Id: GNUmakefile,v 1.1 2001-02-19 23:47:33 whitlock Exp $
#

# example top level makefile... This will just descend to a directory.
default: all

TOPDIR=../..
SUBDIRS=cs410J

include $(TOPDIR)/makefiles/subdirs.gmk

